services:
  proxy_Crosley_10.46.47.196:
    image: proxy
    container_name: proxy_Crosley_10.46.47.196
    networks:
      uc_net:
        ipv4_address: 10.46.47.196
      proxy_net: null
  proxy_Baldwin_10.54.24.230:
    image: proxy
    container_name: proxy_Baldwin_10.54.24.230
    networks:
      uc_net:
        ipv4_address: 10.54.24.230
      proxy_net: null
    tty: true
  debian_Baldwin_10.54.24.105:
    image: debian
    container_name: debian_Baldwin_10.54.24.105
    networks:
      uc_net:
        ipv4_address: 10.54.24.105
    tty: true
  debian_Baldwin_10.54.24.221:
    image: debian
    container_name: debian_Baldwin_10.54.24.221
    networks:
      uc_net:
        ipv4_address: 10.54.24.221
    tty: true
  debian_Baldwin_10.54.24.201:
    image: debian
    container_name: debian_Baldwin_10.54.24.201
    networks:
      uc_net:
        ipv4_address: 10.54.24.201
    tty: true
networks:
  uc_net:
    driver: bridge
    name: uc_net
    ipam:
      driver: default
      config:
      - subnet: 10.0.0.0/9
        gateway: 10.76.0.1
  proxy_net:
    driver: bridge
    name: proxy_net
    ipam:
      driver: default
      config:
      - subnet: 10.128.0.0/9
        gateway: 10.128.0.1
