
services:

  flask_app:
    image: flask_app:local
    build:
      context: ./
      dockerfile: DockerFiles/flask_app.dockerfile
    volumes:
      - type: bind
        source: ./Flask_App/db
        target: /app/db
    ports:
      - "5000:5000"
